---
title: "Build Climate Grid Points"
author: "Will MacKenzie"
date: "2023-12-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
require (smotefamily)
require(data.table)
library(randtoolbox)
library(clhs)
library(ggplot2)
require(sf)
require(caret)
require(ranger)
require(climr)
require(terra)

```

```{r build grid and add elevation}
require(tictoc)
tic()
wna_bgc <- st_read("D:/CommonTables/BGC_Maps/WNA_BGC_v12_5Apr2022.gpkg")
wna_bgc2 <- vect("D:/CommonTables/BGC_Maps/WNA_BGC_v12_5Apr2022.gpkg")# %>% terra::project("EPSG:4326")
wna_grid <- st_make_grid(wna_bgc, cellsize = 2000, what = "centers") %>% st_transform(crs = 4326)
elev <- terra::rast("D:/CommonTables/DEMs/WNA_DEM_SRT_30m.tif") 
wna_grid2 <- vect(wna_grid)
tmp_elev <- terra::extract(elev,wna_grid2)
coords <- geom(wna_grid2, df = T)
coords_only <- coords %>% dplyr::select(x,y)
bgc_coords <- terra::extract(wna_bgc2,coords_only) %>% dplyr::select(BGC)
coords2 <- cbind(bgc_coords, coords)# %>% tidyr::drop_na()
## add BGC
setDT(coords2)
coords2[,c("part","hole","geom") := NULL]
coords2[,elev := tmp_elev[,2]]
coords2[,id := seq_along(elev)]
fwrite(coords2, "./inputs/WNA_2km_grid_BGC.csv")
toc()
###260 seconds
count_tp <- coords2 %>% dplyr::count(BGC)
```

```{r add BGC and climate data}
coords <- fread("./inputs/WNA_2km_grid_BGC.csv") %>% dplyr::select(-BGC)
fwrite(coords,("./inputs/WNA_2km_grid.csv"))
coords <- coords[!is.na(elev),]
coords_sf <- st_as_sf(coords, coords = c("x","y"), crs = 4326)
coords_sf$elev <- NULL
coords_sf <- st_transform(coords_sf, 3005)
#
bgcs <- st_read("D:/CommonTables/BGC_Maps/WNA_BGC_v12_5Apr2022.gpkg")

coords_bgc <- st_join(coords_sf, bgcs, largest = TRUE)
coords_bgc <- data.table(coords_bgc[,c("id","BGC")])
coords_bgc[,geometry := NULL]
#coords_bgc <- coords_bgc[!is.na(BGC),]
# 
# #coords <- fread("WNA_2km_grid_WHM.csv")

coords <- as.data.frame(coords)# %>% dplyr::rename(long = 1, lat = 2)
setcolorder(coords, c("long","lat","elev","id"))
coords.bgc <- coords %>% dplyr::select(id, BGC) %>% dplyr::rename(ID = id)
## based on vs_final below
tic()
clim_vars <- climr_downscale(coords, which_normal = "auto", vars = list_variables(), return_normal = TRUE, cache = TRUE)
toc()

clim_vars2 <- dplyr::left_join(coords.bgc, clim_vars)
setDT(clim_vars2)
clim_vars2 <- clim_vars2[!is.nan(PPT05),] ##lots of points in the ocean
#clim_vars[coords_bgc, BGC := i.BGC, on = c(ID = "id")]
clim_vars2 <- clim_vars2[!is.na(BGC),]
fwrite(clim_vars,"Training_Data_Raw.csv")
clim_vars[,PERIOD := NULL]
clim_vars[,ID := NULL]


```

```{r add climr data to grid}

```

